@startuml RDSSustainabilityMap
entity "Buildings" as buildings {
  id: integer <<primary key>>
  --
  name: string
  map_id: string
  description: integer
  image: integer
  properties: JSON
}

entity "Features" as features {
  id: integer <<primary key>>
  --
  building_id: integer <<foreign key nullable>>
  coordinates: JSON string
  images: JSON string
  description: string
}

entity "Paths" as paths {
  id: integer <<primary key>>
  --
  name: string
  description: integer
}

entity "Path Points" as pathpoints {
  id: integer <<primary key>>
  --
  feature_id: integer <<foreign key nullable>>
  building_id: integer <<foreign key nullable>>
  path_id: integer <<foreign key, not null>>
}
paths }|-- pathpoints
pathpoints }o-- features
pathpoints }o-- buildings
buildings }|-- features
@enduml