@startuml VuexSustainabilityMap
class "Root" as root  {
  --
  - features
  - buildings
  - paths
}

class "Buildings" as buildings {
  - name: string
  - description: integer
  - image: integer
  - properties: Object {\n\
      leed_rank: Integer,\n\
      leed_image: String\n\
    }
  --
  - features
}

class "Features" as features {
  - images: Array <String>
  - description: String
}

class "Layer" as layer {
  - name: string
  - description: integer
  - pathPoint
  --
  ~ features: Array <path ref>
  ~ buildings: Array <path ref>
  ~ pathPoint: Array <path ref>
}

class "Point of Interest" as pointInterest {
  + coordinates: Object {\n\
      lat: Number,\n\
      lng: Number\n\
    }
 - name: String
 - description: integer
   - map_id: string
 --
 ~ features: Array <path ref>
 ~ buildings: Array <path ref>
}

root }o-- layer
layer }o-- pointInterest
pointInterest }|-[dashed]- features
pointInterest }|-- buildings
buildings }|-- features
@enduml
