@startuml VuexSustainabilityMap
class "Root" as root  {
  --
  - features
  - buildings
  - paths
}

class "Buildings" as buildings {
  + name: string
  + map_id: string
  + description: integer
  + image: integer
  + properties: Object {\n\
      leed_rank: Integer,\n\
      leed_image: String\n\
    }
  --
  - features
}

class "Features" as features {
  + images: Array <String>
  + description: String
}

class "Paths" as paths {
  + name: string
  + description: integer
  - pathPoint
  --
  ~ features: Array <path ref>
  ~ buildings: Array <path ref>
  ~ pathPoint: Array <path ref>
}
class "Path Point" as pathPoint {
  + coordinates: Object {\n\
      lat: Number,\n\
      lng: Number\n\
    }
 + name: String
 + description: integer
 --
 ~ features: Array <path ref>
 ~ buildings: Array <path ref>
}
paths }o-right- pathPoint
root }o-right- buildings
root }o-right- paths
pathPoint }|-left[dashed]- features
pathPoint }|-left[dashed]- buildings
buildings }|-- features
@enduml
