language: node_js
node_js:
  - "14"
os: linux
cache:
  directories:n
  - "$HOME/.local"
  - ".cache-loader"
jobs:
  include:
    - stage: build
      name: "Building Project"
      install:
        - npm install
      deploy:
        provider: pages
        local_dir: dist/
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        keep_history: true
        on:
          branch: master
