AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  API routes for the sustainability map

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'localhost'"
        MaxAge: "'600'"
        AllowCredentials: True

Resources:
  Layer:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: app/
      Handler: layer.get
      Layers:
        - arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:92
        - !Ref SusMapModelLayer
      Events:
        Building:
          Type: Api
          Properties:
            Path: /layers
            Method: get
  Points:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: app/
      Handler: point.get
      Layers:
        - arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:92
        - !Ref SusMapModelLayer
      Events:
        Building:
          Type: Api
          Properties:
            Path: /points
            Method: get

  Tag:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: app/
      Handler: layer.get
      Layers:
        - arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:92
        - !Ref SusMapModelLayer
      Events:
        Building:
          Type: Api
          Properties:
            Path: /tag?id=
            Method: get
  SusMapModelLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: SusMapModelLayer
            Description: DB Model Defs
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs6.10
              - nodejs8.10
              - nodejs10.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain
