name: S3 Test Build
on:
  pull_request:
    branches:
      - master

jobs:
  build-deploy-s3:
    name: Build / Deploy to S3 Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm package-lock.json
      - name: npm install
        run: |
          npm install
      - name: npm build frontend
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          npm run build-stage
      - name: deploy frontend to s3
        run: |
          aws s3 sync ./dist s3://sustainability-map
