name: test build
on:
  pull_request:
    branches:
      - master

jobs:
  build-deploy-gh-pages:
    name: Test Build (No Deploy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm install
        run: |
          npm install
      - name: npm build frontend
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          npm run build
