name: test build
on:
  push:
    branches-ignore:
      - master
      - gh-pages

jobs:
  build-deploy-gh-pages:
    name: Test Build (No Deploy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: |
          npm install
      - name: npm build frontend
        run: |
          npm run build-stage