name: test build
on:
  pull_request:
    branches:
      - master

jobs:
  build-deploy-gh-pages:
    name: Test Build (No Deploy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: npm install
        run: |
          npm install
      - name: npm build frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run build-stage